name: Run integration tests

on:
  push:
    paths:
    - lib/**
    - .github/workflows/ci.yml
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: ibnesayeed/setup-ipfs@master
          with:
            run_daemon: true
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14.x'

        - name: Install dependencies
          run: yarn install

        - name: Run tests
          run: yarn test


